
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class Minion : Luban.BeanBase
{
    public Minion(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["name"].IsString) { throw new SerializationException(); }  Name = _buf["name"]; }
        { if(!_buf["asset_name"].IsString) { throw new SerializationException(); }  AssetName = _buf["asset_name"]; }
        { if(!_buf["icon"].IsString) { throw new SerializationException(); }  Icon = _buf["icon"]; }
        { if(!_buf["cost"].IsNumber) { throw new SerializationException(); }  Cost = _buf["cost"]; }
        { if(!_buf["attack"].IsNumber) { throw new SerializationException(); }  Attack = _buf["attack"]; }
        { if(!_buf["hp"].IsNumber) { throw new SerializationException(); }  Hp = _buf["hp"]; }
        { if(!_buf["star"].IsNumber) { throw new SerializationException(); }  Star = _buf["star"]; }
        { if(!_buf["AssociatedCardId"].IsNumber) { throw new SerializationException(); }  AssociatedCardId = _buf["AssociatedCardId"]; }
    }

    public static Minion DeserializeMinion(JSONNode _buf)
    {
        return new Minion(_buf);
    }

    /// <summary>
    /// 卡牌编号
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 名字
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 资源名
    /// </summary>
    public readonly string AssetName;
    /// <summary>
    /// 图标
    /// </summary>
    public readonly string Icon;
    /// <summary>
    /// 费用
    /// </summary>
    public readonly int Cost;
    /// <summary>
    /// 攻击力
    /// </summary>
    public readonly int Attack;
    /// <summary>
    /// 血量
    /// </summary>
    public readonly int Hp;
    /// <summary>
    /// 星级
    /// </summary>
    public readonly int Star;
    /// <summary>
    /// 关联的卡牌编号
    /// </summary>
    public readonly int AssociatedCardId;
   
    public const int __ID__ = -1990171498;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
        
        
        
        
        
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "assetName:" + AssetName + ","
        + "icon:" + Icon + ","
        + "cost:" + Cost + ","
        + "attack:" + Attack + ","
        + "hp:" + Hp + ","
        + "star:" + Star + ","
        + "AssociatedCardId:" + AssociatedCardId + ","
        + "}";
    }
}

}
